"use client";

import { useMemo, useState, useTransition } from "react";
import Link from "next/link";
import { ArrowLeft, Check, FileDown, Plus, Send, Trash2, WandSparkles } from "lucide-react";
import Button from "@/components/ui/Button";
import { findQuoteContactDuplicates, saveQuote, saveQuoteChanges, updateQuoteStatus } from "@/app/presupuestos/quotes/actions";

type CatalogService = { id: string; name: string; description: string | null; prices: Array<{ currency: "EUR" | "MXN"; price: number }> };
type Contact = { id: string; name: string; email: string | null; phone: string | null; instagram: string | null; responsibleId: string | null; stage: "PROSPECT" | "CLIENT" };
type Line = { serviceId: string | null; description: string; quantity: number; unitPrice: number };
type Initial = { id?: string; clientId?: string | null; responsibleId?: string | null; currency?: "EUR" | "MXN" | null; lines?: Line[]; discountType?: "PERCENTAGE" | "FIXED" | null; discountValue?: number | null; taxRatePercent?: number | null; deliveryTimeline?: string | null; salesDescription?: string | null; termsAndConditions?: string | null; depositKind?: "PERCENTAGE" | "FIXED" | "FULL" | "NONE"; depositValue?: number; status?: string; hasProject?: boolean; projectId?: string };

const input = "border-surface-border bg-surface-solid w-full rounded-lg border px-3 py-2 text-sm outline-none focus:border-accent";
function amount(lines: Line[], discountType: string | null, discountValue: number, tax: number) {
  const subtotal = lines.reduce((sum, line) => sum + (Number(line.quantity) || 0) * (Number(line.unitPrice) || 0), 0);
  const discount = discountType === "PERCENTAGE" ? subtotal * discountValue / 100 : discountType === "FIXED" ? Math.min(subtotal, discountValue) : 0;
  const taxAmount = Math.max(0, subtotal - discount) * tax / 100;
  return { subtotal, discount, taxAmount, total: subtotal - discount + taxAmount };
}
function deposit(total: number, kind: string, value: number) { return kind === "NONE" ? 0 : kind === "FULL" ? total : kind === "FIXED" ? Math.min(total, value) : total * value / 100; }

export default function QuoteEditor({ initial = {}, contacts, services, members, isNew = false }: { initial?: Initial; contacts: Contact[]; services: CatalogService[]; members: { id: string; name: string }[]; isNew?: boolean }) {
  const [clientId, setClientId] = useState(initial.clientId ?? "");
  const [newContact, setNewContact] = useState({ name: "", company: "", email: "", phone: "", instagram: "", country: "" });
  const [lines, setLines] = useState<Line[]>(initial.lines?.length ? initial.lines : []);
  const [currency, setCurrency] = useState<"EUR" | "MXN">(initial.currency ?? "EUR");
  const [responsibleId, setResponsibleId] = useState(initial.responsibleId ?? members[0]?.id ?? "");
  const [discountType, setDiscountType] = useState<"PERCENTAGE" | "FIXED" | "">(initial.discountType ?? "");
  const [discountValue, setDiscountValue] = useState(initial.discountValue ?? 0);
  const [taxRatePercent, setTaxRatePercent] = useState(initial.taxRatePercent ?? 0);
  const [deliveryTimeline, setDeliveryTimeline] = useState(initial.deliveryTimeline ?? "");
  const [salesDescription, setSalesDescription] = useState(initial.salesDescription ?? "");
  const [termsAndConditions, setTermsAndConditions] = useState(initial.termsAndConditions ?? "");
  const [depositKind, setDepositKind] = useState(initial.depositKind ?? "PERCENTAGE");
  const [depositValue, setDepositValue] = useState(initial.depositValue ?? 50);
  const [description, setDescription] = useState("");
  const [duplicates, setDuplicates] = useState<Array<{ id: string; name: string }>>([]);
  const [notice, setNotice] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const totals = useMemo(() => amount(lines, discountType || null, Number(discountValue), Number(taxRatePercent)), [lines, discountType, discountValue, taxRatePercent]);
  const selected = contacts.find((item) => item.id === clientId);
  const draft = () => ({ clientId: clientId || null, newContact: clientId ? null : newContact.name ? newContact : null, responsibleId: responsibleId || null, currency, lines, discountType: discountType || null, discountValue: Number(discountValue) || 0, taxRatePercent: Number(taxRatePercent) || 0, deliveryTimeline, salesDescription, termsAndConditions, depositKind, depositValue: Number(depositValue) || 0 });

  function addLine(service?: CatalogService) { setLines((current) => [...current, { serviceId: service?.id ?? null, description: service?.name ?? "Concepto personalizado", quantity: 1, unitPrice: service?.prices.find((price) => price.currency === currency)?.price ?? 0 }]); }
  function updateLine(index: number, patch: Partial<Line>) { setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line)); }
  function selectService(index: number, serviceId: string) { const service = services.find((item) => item.id === serviceId); if (!service) return; updateLine(index, { serviceId, description: service.name, unitPrice: service.prices.find((price) => price.currency === currency)?.price ?? 0 }); }
  function detectDuplicates() { startTransition(async () => { const found = await findQuoteContactDuplicates(newContact); setDuplicates(found); setNotice(found.length ? "Hay contactos coincidentes. Puedes vincular uno en lugar de crear otro." : "No hay coincidencias por contacto."); }); }
  function generate() { startTransition(async () => { setNotice(null); const response = await fetch("/api/quote-proposal", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ description }) }); const data = await response.json(); if (!response.ok) { setNotice(data.error ?? "No pude preparar la propuesta."); return; } const proposal = data.proposal; if (proposal.client && !clientId) setNewContact({ name: proposal.client.name ?? "", company: proposal.client.company ?? "", email: proposal.client.email ?? "", phone: proposal.client.phone ?? "", instagram: proposal.client.instagram ?? "", country: proposal.client.country ?? "" }); if (Array.isArray(data.duplicates)) setDuplicates(data.duplicates); if (proposal.currency === "EUR" || proposal.currency === "MXN") setCurrency(proposal.currency); if (Array.isArray(proposal.lines)) setLines(proposal.lines); setDeliveryTimeline(proposal.deliveryTimeline ?? ""); setSalesDescription(proposal.salesDescription ?? ""); setTermsAndConditions(proposal.termsAndConditions ?? ""); setNotice(data.duplicates?.length ? "Hay contactos coincidentes: vincula uno o revisa antes de guardar." : "Propuesta lista para revisar. No se ha guardado nada todavía."); }); }
  function persist() { startTransition(async () => { try { const form = new FormData(); form.set("quote", JSON.stringify(draft())); if (isNew) await saveQuote(form); else if (initial.id) { await saveQuoteChanges(initial.id, form); setNotice("Cambios guardados."); } } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo guardar el presupuesto."); } }); }
  function changeStatus(status: "READY_TO_SEND" | "SENT" | "ACCEPTED" | "REJECTED" | "EXPIRED") { startTransition(async () => { try { const followUpAt = status === "SENT" ? window.prompt("Seguimiento (AAAA-MM-DDTHH:mm). Déjalo vacío para proponer 3 días.") || null : null; const reason = ["REJECTED", "EXPIRED"].includes(status) ? window.prompt("Razón opcional") || undefined : undefined; await updateQuoteStatus(initial.id!, status, { followUpAt, reason }); setNotice(status === "ACCEPTED" ? "Presupuesto aprobado. Ya puedes preparar el proyecto en la siguiente fase." : "Estado actualizado."); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo cambiar el estado."); } }); }

  return <div className="relative flex h-full flex-col overflow-y-auto px-4 py-6 sm:px-10 lg:px-16"><div className="mx-auto w-full max-w-6xl space-y-5 pb-10"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/presupuestos" className="text-muted-foreground inline-flex items-center gap-1 text-sm"><ArrowLeft className="h-4 w-4" />Presupuestos</Link><h1 className="mt-2 text-2xl font-semibold">{isNew ? "Nuevo presupuesto" : "Editar presupuesto"}</h1><p className="text-muted-foreground text-sm">La IA propone; el equipo revisa y confirma.</p></div>{!isNew && initial.id ? <div className="flex flex-wrap gap-2"><a href={`/api/quotes/${initial.id}/pdf`} className="border-surface-border inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><FileDown className="h-4 w-4" />PDF</a>{initial.hasProject ? <Link href={`/projects/${initial.projectId}`} className="rounded-lg border px-3 py-2 text-sm">Ver proyecto</Link> : initial.status === "ACCEPTED" ? <span className="rounded-lg bg-emerald-500/10 px-3 py-2 text-sm text-emerald-300">Preparar proyecto · Fase 3</span> : null}</div> : null}</div>
    {notice ? <p className="rounded-xl border border-accent/30 bg-accent-soft px-3 py-2 text-sm">{notice}</p> : null}
    {isNew ? <section className="liquid-glass rounded-2xl p-5"><label className="text-sm font-medium">Describe lo que necesita el cliente</label><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Ej.: Landing para una cafetería en Madrid, cinco secciones y entrega en dos semanas." className={`${input} mt-2 min-h-24`} /><Button type="button" className="mt-3" onClick={generate} disabled={pending || !description.trim()}><WandSparkles className="h-4 w-4" />{pending ? "Preparando…" : "Proponer con IA"}</Button><p className="text-muted-foreground mt-2 text-xs">Abrir, cerrar o refrescar este asistente no crea un presupuesto.</p></section> : null}
    <section className="grid gap-5 lg:grid-cols-2"><div className="liquid-glass rounded-2xl p-5"><h2 className="font-semibold">Contacto</h2><select value={clientId} onChange={(event) => { setClientId(event.target.value); const contact = contacts.find((item) => item.id === event.target.value); if (contact?.responsibleId) setResponsibleId(contact.responsibleId); }} className={`${input} mt-3`}><option value="">Proponer contacto nuevo</option>{contacts.map((contact) => <option key={contact.id} value={contact.id}>{contact.name} · {contact.stage === "PROSPECT" ? "Prospecto" : "Cliente"}</option>)}</select>{selected ? <p className="text-muted-foreground mt-2 text-xs">{selected.email ?? selected.phone ?? selected.instagram ?? "Sin contacto"}</p> : <div className="mt-3 grid gap-2 sm:grid-cols-2"><input value={newContact.name} onChange={(e) => setNewContact({ ...newContact, name: e.target.value })} className={input} placeholder="Nombre *"/><input value={newContact.company} onChange={(e) => setNewContact({ ...newContact, company: e.target.value })} className={input} placeholder="Empresa"/><input value={newContact.email} onChange={(e) => setNewContact({ ...newContact, email: e.target.value })} className={input} placeholder="Email"/><input value={newContact.phone} onChange={(e) => setNewContact({ ...newContact, phone: e.target.value })} className={input} placeholder="Teléfono / WhatsApp"/><input value={newContact.instagram} onChange={(e) => setNewContact({ ...newContact, instagram: e.target.value })} className={input} placeholder="Instagram"/><input value={newContact.country} onChange={(e) => setNewContact({ ...newContact, country: e.target.value })} className={input} placeholder="País"/><button type="button" onClick={detectDuplicates} className="text-accent text-left text-xs underline sm:col-span-2">Buscar coincidencias</button>{duplicates.map((item) => <button type="button" key={item.id} onClick={() => { setClientId(item.id); setDuplicates([]); }} className="rounded border border-amber-400/30 px-2 py-1 text-left text-xs sm:col-span-2">Usar coincidencia: {item.name}</button>)}</div>}<label className="mt-4 block text-sm">Responsable<select value={responsibleId} onChange={(event) => setResponsibleId(event.target.value)} className={`${input} mt-1`}>{members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label></div>
      <div className="liquid-glass rounded-2xl p-5"><h2 className="font-semibold">Condiciones</h2><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm">Moneda<select value={currency} onChange={(e) => setCurrency(e.target.value as "EUR" | "MXN")} className={`${input} mt-1`}><option value="EUR">EUR</option><option value="MXN">MXN</option></select></label><label className="text-sm">Impuesto %<input value={taxRatePercent} type="number" min="0" onChange={(e) => setTaxRatePercent(Number(e.target.value))} className={`${input} mt-1`}/></label><label className="text-sm">Descuento<select value={discountType} onChange={(e) => setDiscountType(e.target.value as "PERCENTAGE" | "FIXED" | "")} className={`${input} mt-1`}><option value="">Sin descuento</option><option value="PERCENTAGE">Porcentaje</option><option value="FIXED">Importe fijo</option></select></label><label className="text-sm">Valor descuento<input value={discountValue} type="number" min="0" onChange={(e) => setDiscountValue(Number(e.target.value))} className={`${input} mt-1`}/></label><label className="text-sm">Anticipo<select value={depositKind} onChange={(e) => setDepositKind(e.target.value as typeof depositKind)} className={`${input} mt-1`}><option value="PERCENTAGE">Porcentaje</option><option value="FIXED">Importe fijo</option><option value="FULL">Pago completo</option><option value="NONE">Sin anticipo</option></select></label><label className="text-sm">Valor<input value={depositValue} type="number" min="0" onChange={(e) => setDepositValue(Number(e.target.value))} disabled={depositKind === "FULL" || depositKind === "NONE"} className={`${input} mt-1`}/></label></div><label className="mt-3 block text-sm">Plazo<input value={deliveryTimeline} onChange={(e) => setDeliveryTimeline(e.target.value)} className={`${input} mt-1`} placeholder="Ej. 10 días hábiles"/></label></div></section>
    <section className="liquid-glass rounded-2xl p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Servicios y precios</h2><Button type="button" variant="secondary" onClick={() => addLine()}><Plus className="h-4 w-4" />Añadir línea</Button></div><div className="mt-4 space-y-3">{lines.map((line, index) => <div key={index} className="grid gap-2 rounded-xl border border-surface-border p-3 md:grid-cols-[1.4fr_2fr_.7fr_1fr_auto]"><select value={line.serviceId ?? ""} onChange={(e) => selectService(index, e.target.value)} className={input}><option value="">Personalizado</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><input value={line.description} onChange={(e) => updateLine(index, { description: e.target.value })} className={input} placeholder="Descripción"/><input type="number" min="0.01" value={line.quantity} onChange={(e) => updateLine(index, { quantity: Number(e.target.value) })} className={input}/><input type="number" min="0" value={line.unitPrice} onChange={(e) => updateLine(index, { unitPrice: Number(e.target.value) })} className={input}/><button type="button" onClick={() => setLines((current) => current.filter((_, lineIndex) => lineIndex !== index))} className="text-muted-foreground p-2"><Trash2 className="h-4 w-4"/></button></div>)}{lines.length === 0 ? <p className="text-muted-foreground text-sm">Añade una línea manualmente o genera una propuesta con IA.</p> : null}</div></section>
    <section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="liquid-glass rounded-2xl p-5"><label className="block text-sm font-medium">Descripción comercial<textarea value={salesDescription} onChange={(e) => setSalesDescription(e.target.value)} className={`${input} mt-1 min-h-20`} /></label><label className="mt-3 block text-sm font-medium">Notas y condiciones<textarea value={termsAndConditions} onChange={(e) => setTermsAndConditions(e.target.value)} className={`${input} mt-1 min-h-20`} /></label></div><aside className="liquid-glass rounded-2xl p-5"><h2 className="font-semibold">Totales</h2><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{totals.subtotal.toFixed(2)} {currency}</dd></div><div className="flex justify-between"><dt>Descuento</dt><dd>-{totals.discount.toFixed(2)}</dd></div><div className="flex justify-between"><dt>Impuesto</dt><dd>{totals.taxAmount.toFixed(2)}</dd></div><div className="flex justify-between border-t border-surface-border pt-2 font-semibold"><dt>Total</dt><dd>{totals.total.toFixed(2)} {currency}</dd></div><div className="flex justify-between text-accent"><dt>Anticipo</dt><dd>{deposit(totals.total, depositKind, Number(depositValue)).toFixed(2)} {currency}</dd></div><div className="flex justify-between"><dt>Saldo</dt><dd>{(totals.total - deposit(totals.total, depositKind, Number(depositValue))).toFixed(2)} {currency}</dd></div></dl><Button type="button" className="mt-5 w-full" onClick={persist} disabled={pending}><Check className="h-4 w-4" />{isNew ? "Confirmar y guardar" : "Guardar cambios"}</Button></aside></section>
    {!isNew && initial.id ? <section className="liquid-glass flex flex-wrap gap-2 rounded-2xl p-5"><Button type="button" variant="secondary" onClick={() => changeStatus("READY_TO_SEND")} disabled={pending}>Listo para enviar</Button><Button type="button" variant="secondary" onClick={() => changeStatus("SENT")} disabled={pending}><Send className="h-4 w-4"/>Marcar enviado</Button><Button type="button" variant="secondary" onClick={() => changeStatus("ACCEPTED")} disabled={pending}>Aprobar</Button><Button type="button" variant="ghost" onClick={() => changeStatus("REJECTED")} disabled={pending}>Rechazar</Button><Button type="button" variant="ghost" onClick={() => changeStatus("EXPIRED")} disabled={pending}>Vencer</Button></section> : null}
  </div></div>;
}
