// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Supabase usa dos connection strings distintas:
// - DIRECT_URL (puerto 5432, sin pooling): la usa el CLI de Prisma para migrate/db push.
// - DATABASE_URL (puerto 6543, pgbouncer): la usa la app en tiempo de ejecución (src/lib/prisma.ts).
// Ver .env.example y README.md para el detalle de dónde obtener cada una.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
