import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { PGlite } from "@electric-sql/pglite";
import { PGLiteSocketServer } from "@electric-sql/pglite-socket";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { runWorkCommand, archiveClientRecord } from "../src/lib/work-service";
import { financialSummary, nextMonthDate } from "../src/lib/work-finance";
import { isActiveProject } from "../src/lib/project-status";
import { projectAttention } from "../src/lib/workspace-summary";
import { prepareProjectFromQuote } from "../src/lib/project-preparation-service";
import { getProjectAgendaItems } from "../src/lib/project-agenda-items";

// Always creates an isolated in-memory PostgreSQL instance. Never reads DATABASE_URL.
async function main() {
  const pg = new PGlite();
  const migrations = (await readdir("prisma/migrations")).filter((name) => /^\d/.test(name)).sort();
  for (const name of migrations.slice(0, -1)) await pg.exec(await readFile(`prisma/migrations/${name}/migration.sql`, "utf8"));
  await pg.exec(`INSERT INTO users (id,email,"displayName","updatedAt") VALUES ('owner','owner@test.invalid','Owner',now()),('other','other@test.invalid','Other',now());
    INSERT INTO clients (id,name,"updatedAt") VALUES ('client','Legacy client',now());
    INSERT INTO projects (id,"userId",name,client,status,progress,"updatedAt") VALUES ('legacy','owner','Legacy project','Legacy client','DONE',80,now());
    INSERT INTO quotes (id,"userId","clientId",status,"updatedAt") VALUES ('quote','owner','client','PAID',now());`);
  const before = await pg.query('SELECT id,name,status,progress,client FROM projects');
  await pg.exec(await readFile(`prisma/migrations/${migrations.at(-1)}/migration.sql`, "utf8"));
  assert.deepEqual(await pg.query('SELECT id,name,status,progress,client FROM projects'), before, "migration preserves all original project values");
  const server = new PGLiteSocketServer({ db: pg, host: "127.0.0.1", port: 0 });
  await server.start();
  const conn = `postgresql://postgres@${server.getServerConn()}/postgres`;
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: conn, max: 1 }) });
  let checks = 0;
  const check = (label: string) => { checks++; console.log(`✓ ${label}`); };
  const form = (command: string, fields: Record<string, string> = {}) => { const f = new FormData(); f.set("command", command); for (const [key, value] of Object.entries(fields)) f.set(key, value); return f; };
  const ownerActor = { userId: "owner", workspaceId: "workspace", role: "ADMIN" as const };
  const memberActor = { userId: "other", workspaceId: "workspace", role: "MEMBER" as const };
  const command = (id: string, action: string, fields: Record<string, string> = {}) => runWorkCommand(db, ownerActor, id, form(action, fields));
  try {
    const legacy = await db.project.findUniqueOrThrow({ where: { id: "legacy" } });
    assert.equal(legacy.status, "DONE"); assert.equal(legacy.kind, "ONE_OFF"); assert.equal(legacy.clientId, null);
    assert.equal(await db.payment.count(), 0); assert.equal(await db.activityRecord.count(), 0);
    assert.equal((await db.quote.findUniqueOrThrow({ where: { id: "quote" } })).status, "PAID");
    check("additive migration preserves old states, quote PAID and free-text client; no invented payments/activity");
    await db.workspace.create({ data: { id: "workspace", name: "Test workspace" } });
    await db.workspaceMember.createMany({ data: [
      { id: "owner-member", workspaceId: "workspace", userId: "owner", role: "ADMIN" },
      { id: "other-member", workspaceId: "workspace", userId: "other", role: "MEMBER" },
    ] });
    await db.client.update({ where: { id: "client" }, data: { workspaceId: "workspace" } });
    await db.quote.update({ where: { id: "quote" }, data: { workspaceId: "workspace" } });
    await db.quote.create({ data: { id: "approved", workspaceId: "workspace", userId: "owner", clientId: "client", responsibleId: "owner", currency: "EUR", status: "ACCEPTED", total: "200", depositKind: "PERCENTAGE", depositValue: "50", lineItems: { create: [{ description: "Branding", quantity: "1", unitPrice: "200", lineTotal: "200" }] } } });
    const projectsBeforePreparation = await db.project.count();
    const prepared = await prepareProjectFromQuote(db, ownerActor, { quoteId: "approved", name: "Branding launch", kind: "RECURRING", startDate: "2026-09-01", dueDate: "2026-09-30", agreedTotal: "200", depositExpected: "100", responsibleId: "owner", tasks: [{ title: "Diseñar identidad", responsibleId: "other", dueDate: "2026-09-10", needsReview: true }] });
    assert.equal(await db.project.count(), projectsBeforePreparation + 1);
    assert.equal(prepared.created, true);
    const retry = await prepareProjectFromQuote(db, ownerActor, { quoteId: "approved", name: "Ignored retry", kind: "ONE_OFF", startDate: null, dueDate: null, agreedTotal: "200", depositExpected: "100", responsibleId: "owner", tasks: [] });
    assert.equal(retry.id, prepared.id); assert.equal(retry.created, false);
    const preparedProject = await db.project.findUniqueOrThrow({ where: { id: prepared.id }, include: { periods: true, workItems: true } });
    assert.equal(preparedProject.status, "NOT_STARTED"); assert.equal(preparedProject.periods.length, 1); assert.equal(preparedProject.workItems[0]?.needsReview, true); assert.equal(preparedProject.workItems[0]?.responsibleId, "other");
    check("reviewed preparation creates project, initial monthly period and editable task data only on confirmation; retries do not duplicate it");
    const preparedPeriod = preparedProject.periods[0]!;
    await command(prepared.id, "payment", { periodId: preparedPeriod.id, amount: "40", type: "DEPOSIT", paidAt: "2026-09-02", requestId: "deposit-partial" });
    assert.equal((await db.project.findUniqueOrThrow({ where: { id: prepared.id } })).status, "NOT_STARTED");
    await command(prepared.id, "payment", { periodId: preparedPeriod.id, amount: "60", type: "DEPOSIT", paidAt: "2026-09-03", requestId: "deposit-final" });
    assert.equal((await db.project.findUniqueOrThrow({ where: { id: prepared.id } })).status, "IN_PROGRESS");
    await assert.rejects(runWorkCommand(db, memberActor, prepared.id, form("activate", { periodId: preparedPeriod.id, confirmation: "ACTIVAR" })), /administrador/);
    assert.equal((await db.quote.findUniqueOrThrow({ where: { id: "approved" } })).status, "ACCEPTED");
    check("partial deposits keep project prepared; complete deposit activates it without changing the approved quote and only admins can activate manually");
    await db.project.create({ data: { id: "one", workspaceId: "workspace", userId: "owner", name: "Website", client: "Legacy client", clientId: "client", dueDate: new Date("2020-01-01") } });
    await command("one", "finance", { agreedTotal: "100.10", currency: "EUR", paymentDueDate: "2020-01-01" });
    await command("one", "dates", { startDate: "2026-09-01", dueDate: "2026-09-15" });
    let agendaDates = await getProjectAgendaItems(db, "workspace");
    assert.ok(agendaDates.some((item) => item.projectId === "one" && item.agendaKind === "PROJECT_START"));
    assert.ok(agendaDates.some((item) => item.projectId === "one" && item.agendaKind === "PROJECT_DUE"));
    assert.equal(await db.event.count({ where: { projectId: "one" } }), 0);
    await command("one", "dates", { startDate: "2026-09-01", dueDate: "" });
    agendaDates = await getProjectAgendaItems(db, "workspace");
    assert.equal(agendaDates.some((item) => item.projectId === "one" && item.agendaKind === "PROJECT_DUE"), false);
    check("project start and delivery appear in Agenda as derived all-day items, move with dates and never create duplicate events");
    await command("one", "status", { status: "DELIVERED" });
    let project = await db.project.findUniqueOrThrow({ where: { id: "one" } });
    assert.equal(project.progress, 0); assert.equal(await db.payment.count({ where: { projectId: "one" } }), 0);
    assert.equal(projectAttention(project, "2026-09-07"), null);
    check("delivery removes overdue warning and changes neither progress nor payment");
    await command("one", "payment", { amount: "30.05", paidAt: "2026-01-01", requestId: "partial-one" });
    await command("one", "payment", { amount: "30.05", paidAt: "2026-01-01", requestId: "partial-one" });
    assert.equal(await db.payment.count({ where: { projectId: "one" } }), 1);
    assert.deepEqual(financialSummary("100.10", ["30.05"], null, "2026-09-07"), { status: "Parcial", paid: "30.05", outstanding: "70.05", credit: "0.00" });
    assert.equal(financialSummary("100.10", ["30.05"], "2020-01-01", "2026-09-07").status, "Vencido");
    await command("one", "payment", { amount: "70.05", paidAt: "2026-01-02", requestId: "final-one" });
    assert.equal(financialSummary("100.10", ["30.05", "70.05"], "2020-01-01", "2026-09-07").status, "Pagado");
    await assert.rejects(command("one", "finance", { currency: "MXN", agreedTotal: "100.10" }), /moneda/);
    await assert.rejects(command("one", "payment", { amount: "0", paidAt: "2026-01-01", requestId: "zero" }));
    await assert.rejects(command("one", "payment", { amount: "10.001", paidAt: "2026-01-01", requestId: "precision" }));
    check("multiple partial payments, exact cents, overdue balances and idempotent retries");
    await command("one", "status", { status: "CLOSED" });
    project = await db.project.findUniqueOrThrow({ where: { id: "one" } });
    assert.equal(isActiveProject(project), false);
    await command("one", "status", { status: "PAUSED" });
    project = await db.project.findUniqueOrThrow({ where: { id: "one" } });
    assert.equal(projectAttention(project, "2026-09-07"), null);
    check("closed projects leave active view; paused projects have no overdue delivery warning");
    await db.project.create({ data: { id: "monthly", workspaceId: "workspace", userId: "owner", name: "Social", client: "Legacy client", clientId: "client", kind: "RECURRING" } });
    const first = await command("monthly", "createPeriod", { label: "August", startDate: "2026-08-01", dueDate: "2026-08-31" });
    assert.ok(first);
    await command("monthly", "finance", { periodId: first, currency: "EUR", agreedTotal: "300", paymentDueDate: "2026-08-31" });
    await command("monthly", "addWork", { periodId: first, title: "Design cover", recurring: "on", dueDate: "2026-08-15" });
    await command("monthly", "addWork", { periodId: first, title: "Deliver files", kind: "DELIVERABLE" });
    const work = await db.workItem.findFirstOrThrow({ where: { periodId: first, kind: "TASK" } });
    await command("monthly", "toggleWork", { periodId: first, itemId: work.id, completed: "true" });
    await command("monthly", "assign", { periodId: first, userId: "other" });
    await command("monthly", "payment", { periodId: first, amount: "300", paidAt: "2026-08-01", requestId: "august-payment" });
    await command("monthly", "status", { periodId: first, status: "CLOSED" });
    const parent = await db.project.findUniqueOrThrow({ where: { id: "monthly" } });
    assert.equal(parent.relationshipStatus, "ACTIVE"); assert.equal(parent.status, "NOT_STARTED");
    const second = await command("monthly", "createPeriod", { label: "September", startDate: "2026-09-01", sourceId: first, copyPrice: "on", copyTeam: "on", copyTasks: "on", copyConfig: "on" });
    assert.ok(second);
    const next = await db.projectPeriod.findUniqueOrThrow({ where: { id: second }, include: { payments: true, workItems: true, assignments: true } });
    assert.equal(next.status, "NOT_STARTED"); assert.equal(next.agreedTotal?.toFixed(2), "300.00");
    assert.equal(next.payments.length, 0); assert.equal(next.workItems.length, 1); assert.equal(next.workItems[0].completedAt, null); assert.equal(next.assignments.length, 1);
    assert.equal(financialSummary(next.agreedTotal!.toFixed(2), [], null, "2026-09-07").status, "Pendiente");
    assert.equal(next.workItems[0].dueDate?.toISOString().slice(0, 10), "2026-09-15");
    check("closing August preserves active parent; September optionally copies price, team and recurring tasks without payments/completion");
    const empty = await command("monthly", "createPeriod", { label: "October", startDate: "2026-10-01" });
    assert.ok(empty);
    const blank = await db.projectPeriod.findUniqueOrThrow({ where: { id: empty }, include: { workItems: true, assignments: true } });
    assert.equal(blank.agreedTotal, null); assert.equal(blank.workItems.length, 0); assert.equal(blank.assignments.length, 0);
    const structure = await command("monthly", "createPeriod", { label: "November", startDate: "2026-11-01", sourceId: first, copyStructure: "on" });
    assert.equal(await db.workItem.count({ where: { periodId: structure } }), 2);
    await assert.rejects(command("monthly", "createPeriod", { label: "Duplicate", startDate: "2026-09-01" }), /existe/);
    await assert.rejects(command("one", "createPeriod", { label: "Invalid", startDate: "2026-01-01" }), /único/);
    await assert.rejects(command("monthly", "payment", { amount: "1", paidAt: "2026-01-01", requestId: "root-payment" }), /periodo/);
    await assert.rejects(command("one", "payment", { periodId: first, amount: "1", paidAt: "2026-01-01", requestId: "wrong-period" }), /pertenece/);
    await runWorkCommand(db, memberActor, "monthly", form("dates", { periodId: first, dueDate: "2026-08-31" }));
    await db.workspace.create({ data: { id: "other-workspace", name: "Other workspace" } });
    await db.workspaceMember.create({ data: { id: "other-workspace-member", workspaceId: "other-workspace", userId: "other", role: "ADMIN" } });
    await db.project.create({ data: { id: "foreign", workspaceId: "other-workspace", userId: "other", name: "Foreign", client: "Foreign client" } });
    assert.equal(await db.project.findFirst({ where: { id: "foreign", workspaceId: "workspace" } }), null);
    await assert.rejects(command("foreign", "status", { status: "IN_PROGRESS" }), /acceso/);
    check("same-workspace members can update shared work; a direct foreign project ID is rejected");
    await db.project.create({ data: { id: "convert", workspaceId: "workspace", userId: "owner", name: "Existing retainer", client: "Legacy client", clientId: "client", status: "IN_PROGRESS", dueDate: new Date("2026-12-31"), agreedTotal: "90", currency: "EUR" } });
    await command("convert", "addWork", { title: "Existing task" });
    await command("convert", "payment", { amount: "20", paidAt: "2026-09-01", requestId: "existing-payment" });
    await command("convert", "assign", { userId: "other" });
    const convertedPeriod = await command("convert", "convertRecurring", { label: "Current cycle", startDate: "2026-09-01" });
    const converted = await db.project.findUniqueOrThrow({ where: { id: "convert" }, include: { periods: true, payments: true, workItems: true, assignments: true } });
    assert.equal(converted.kind, "RECURRING"); assert.equal(converted.periods[0].status, "IN_PROGRESS");
    assert.equal(converted.payments[0].periodId, convertedPeriod); assert.equal(converted.workItems[0].periodId, convertedPeriod);
    assert.ok(converted.assignments.some((a) => a.periodId === null)); assert.ok(converted.assignments.some((a) => a.periodId === convertedPeriod));
    check("explicit one-off conversion preserves current state, dates, payment, tasks and default team in its first period");
    const counts = [await db.project.count(), await db.projectPeriod.count(), await db.payment.count(), await db.quote.count(), await db.workItem.count()];
    await assert.rejects(archiveClientRecord(db, memberActor, "client", true), /administrador/);
    const assignment = await db.workAssignment.findFirstOrThrow({ where: { projectId: "monthly", periodId: first } });
    await assert.rejects(runWorkCommand(db, memberActor, "monthly", form("unassign", { periodId: first, assignmentId: assignment.id })), /administrador/);
    await archiveClientRecord(db, ownerActor, "client", true);
    assert.ok((await db.client.findUniqueOrThrow({ where: { id: "client" } })).archivedAt);
    assert.deepEqual([await db.project.count(), await db.projectPeriod.count(), await db.payment.count(), await db.quote.count(), await db.workItem.count()], counts);
    await archiveClientRecord(db, ownerActor, "client", false);
    assert.equal((await db.client.findUniqueOrThrow({ where: { id: "client" } })).archivedAt, null);
    assert.equal(await db.activityRecord.count({ where: { action: "CLIENT_ARCHIVED" } }), 1);
    const paymentEvents = await db.activityRecord.count({ where: { action: "PAYMENT_RECORDED" } });
    assert.equal(paymentEvents, await db.payment.count());
    assert.ok(await db.activityRecord.count({ where: { actorId: "other" } }));
    assert.equal(await db.workItem.count({ where: { workspaceId: "workspace" } }), await db.workItem.count());
    check("only admins archive; root work records keep workspace and activities preserve their actor");
    assert.equal(nextMonthDate("2026-01-31"), "2026-02-28");
    assert.equal(nextMonthDate("2028-01-31"), "2028-02-29");
    assert.equal(financialSummary(null, ["10.00"], null, "2026-01-01").outstanding, null);
    assert.equal(financialSummary("10", ["12.30"], null, "2026-01-01").credit, "2.30");
    check("month-end/leap-year dates, unknown totals and overpayment credit");
    await assert.rejects(db.payment.create({ data: { id: randomUUID(), requestId: randomUUID(), projectId: "monthly", amount: "1", currency: "EUR", paidAt: new Date(), recordedById: "owner" } }));
    await assert.rejects(db.payment.create({ data: { id: randomUUID(), requestId: randomUUID(), projectId: "one", periodId: first, amount: "1", currency: "EUR", paidAt: new Date(), recordedById: "owner" } }));
    await assert.rejects(db.projectPeriod.delete({ where: { id: first } }));
    await assert.rejects(db.client.delete({ where: { id: "client" } }));
    check("database constraints reject wrong payment scope and deletion of referenced records");
    console.log(`${checks} integration groups passed across ${migrations.length} migrations. No external database used.`);
  } finally { await db.$disconnect(); await server.stop(); await pg.close(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
