import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { PGLiteSocketServer } from "@electric-sql/pglite-socket";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { backfillQuotePhase2, verifyQuotePhase2Backfill } from "../src/lib/quote-phase2-backfill";
import { changeQuoteStatus, createQuoteFromDraft, depositAmount, quoteTotals } from "../src/lib/quote-workflow-service";

async function main() {
 const pg = new PGlite(); const migrations = (await readdir("prisma/migrations")).filter((name) => /^\d/.test(name)).sort(); for (const migration of migrations) await pg.exec(await readFile(`prisma/migrations/${migration}/migration.sql`, "utf8"));
 const server = new PGLiteSocketServer({ db: pg, host: "127.0.0.1", port: 0 }); await server.start(); const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: `postgresql://postgres@${server.getServerConn()}/postgres`, max: 1 }) });
 const admin = { userId: "admin", workspaceId: "workspace", role: "ADMIN" as const }; const member = { userId: "member", workspaceId: "workspace", role: "MEMBER" as const };
 try {
  await db.user.createMany({ data: [{ id: "admin", email: "admin@example.test", displayName: "Admin" }, { id: "member", email: "member@example.test", displayName: "Member" }, { id: "foreign", email: "foreign@example.test", displayName: "Foreign" }] });
  await db.workspace.createMany({ data: [{ id: "workspace", name: "Diseño Creativo" }, { id: "other", name: "Other" }] }); await db.workspaceMember.createMany({ data: [{ id: "a", workspaceId: "workspace", userId: "admin", role: "ADMIN" }, { id: "m", workspaceId: "workspace", userId: "member", role: "MEMBER" }, { id: "f", workspaceId: "other", userId: "foreign", role: "ADMIN" }] });
  await db.service.create({ data: { id: "service", workspaceId: "workspace", name: "Landing", category: "Web", pricingRules: { create: { currency: "EUR", basePrice: "100" } } } }); await db.client.create({ data: { id: "prospect", workspaceId: "workspace", name: "Ana", email: "ana@example.test", emailNormalized: "ana@example.test", stage: "PROSPECT", prospectStatus: "NEW", responsibleId: "member" } });
  assert.deepEqual(quoteTotals({ lines: [{ description: "Landing", quantity: 2, unitPrice: 100 }], discountType: "PERCENTAGE", discountValue: 10, taxRatePercent: 0 }), { subtotal: 200, discount: 20, taxAmount: 0, total: 180, taxRatePercent: 0 }); assert.equal(depositAmount(180, "PERCENTAGE", 50), 90); assert.equal(depositAmount(180, "FIXED", 40), 40);
  const before = await db.quote.count(); assert.equal(before, 0); console.log("✓ abrir el asistente no tiene operación de persistencia asociada");
  const quote = await createQuoteFromDraft(db, member, { clientId: "prospect", responsibleId: "member", currency: "EUR", lines: [{ serviceId: "service", description: "Landing", quantity: 1, unitPrice: 150 }], depositKind: "PERCENTAGE", depositValue: 50 }); assert.equal(await db.quote.count(), 1); assert.equal(quote.userId, "member"); assert.equal(quote.workspaceId, "workspace"); assert.equal((await db.client.findUniqueOrThrow({ where: { id: "prospect" } })).prospectStatus, "QUOTE"); console.log("✓ cliente preseleccionado, precio editable y anticipo 50% se guardan sin tocar catálogo"); assert.equal((await db.pricingRule.findFirstOrThrow({ where: { serviceId: "service" } })).basePrice.toString(), "100");
  await db.client.create({ data: { id: "duplicate", workspaceId: "workspace", name: "Duplicada", email: "dup@example.test", emailNormalized: "dup@example.test", stage: "PROSPECT", prospectStatus: "NEW", responsibleId: "admin" } }); await assert.rejects(createQuoteFromDraft(db, admin, { newContact: { name: "Nueva", email: "dup@example.test" }, currency: "EUR", lines: [{ description: "Diseño", quantity: 1, unitPrice: 10 }] }), /coincidente/); assert.equal(await db.client.count({ where: { workspaceId: "workspace" } }), 2); console.log("✓ propuesta de contacto no crea duplicado hasta confirmación explícita");
  const newQuote = await createQuoteFromDraft(db, admin, { newContact: { name: "Contacto nuevo", email: "nuevo@example.test" }, currency: "EUR", lines: [{ description: "Concepto personalizado", quantity: 1, unitPrice: 30 }] }); assert.equal((await db.client.findUniqueOrThrow({ where: { id: newQuote.clientId! } })).stage, "PROSPECT"); console.log("✓ propuesta de contacto nuevo solo se crea al confirmar el presupuesto");
  await assert.rejects(changeQuoteStatus(db, member, quote.id, "ARCHIVED"), /administrador/);
  await changeQuoteStatus(db, member, quote.id, "SENT", { followUpAt: new Date("2026-10-01T09:00:00Z") }); assert.equal(await db.event.count({ where: { workspaceId: "workspace", quoteId: quote.id, type: "FOLLOW_UP" } }), 1); await changeQuoteStatus(db, member, quote.id, "ACCEPTED"); const converted = await db.client.findUniqueOrThrow({ where: { id: "prospect" } }); assert.equal(converted.stage, "CLIENT"); assert.equal(await db.project.count(), 0); assert.ok(await db.quoteStatusHistory.count({ where: { quoteId: quote.id, changedById: "member" } })); console.log("✓ enviado agenda seguimiento; aprobar convierte prospecto sin crear proyecto y registra actor");
  await assert.rejects(changeQuoteStatus(db, { userId: "foreign", workspaceId: "other", role: "ADMIN" }, quote.id, "REJECTED"), /no disponible/); console.log("✓ ID directo de otro workspace no permite modificar presupuesto");
  const old = await db.quote.create({ data: { id: "old", workspaceId: "workspace", userId: "admin", clientId: "prospect", statusHistory: { create: { status: "DRAFT" } } } }); assert.equal((await backfillQuotePhase2(db, "workspace", true)).quotes, 1); await backfillQuotePhase2(db, "workspace"); assert.equal((await db.quote.findUniqueOrThrow({ where: { id: old.id } })).responsibleId, "member"); assert.equal((await verifyQuotePhase2Backfill(db, "workspace")).ok, true); console.log("✓ backfill aditivo conserva presupuestos históricos y es verificable");
 } finally { await db.$disconnect(); await server.stop(); await pg.close(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
