import Link from "next/link";
import { Plus } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireWorkspaceMembership } from "@/lib/workspace-access";
import DashboardBackground from "@/components/dashboard/DashboardBackground";
import { QUOTE_STATUS_CONFIG } from "@/lib/quote-status";

export default async function QuotesPage({ searchParams }: { searchParams: Promise<{ status?: string; q?: string }> }) {
  const { workspace } = await requireWorkspaceMembership();
  const query = await searchParams;
  const statuses = ["DRAFT", "READY_TO_SEND", "SENT", "ACCEPTED", "REJECTED", "EXPIRED"] as const;
  const selected = statuses.includes(query.status as typeof statuses[number]) ? query.status as typeof statuses[number] : undefined;
  const q = query.q?.trim();
  const quotes = await prisma.quote.findMany({ where: { workspaceId: workspace.id, ...(selected ? { status: selected } : { status: { not: "ARCHIVED" } }), ...(q ? { OR: [{ client: { name: { contains: q, mode: "insensitive" } } }, { salesDescription: { contains: q, mode: "insensitive" } }] } : {}) }, include: { client: { select: { name: true } }, responsible: { select: { displayName: true } }, events: { where: { type: "FOLLOW_UP" }, orderBy: { startAt: "desc" }, take: 1 }, projects: { select: { id: true } } }, orderBy: { updatedAt: "desc" } });
  return <div className="relative flex h-full flex-col overflow-y-auto px-4 py-6 sm:px-10 lg:px-16"><DashboardBackground /><div className="mx-auto w-full max-w-6xl pb-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Presupuestos</h1><p className="text-muted-foreground mt-1 text-sm">Propuestas, seguimiento y aprobación del estudio.</p></div><Link href="/presupuestos/nuevo" className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-medium text-white"><Plus className="h-4 w-4"/>Nuevo presupuesto</Link></div><form className="mt-5 flex flex-wrap gap-2"><input name="q" defaultValue={q} placeholder="Buscar cliente o propuesta" className="border-surface-border bg-surface-solid rounded-lg border px-3 py-2 text-sm"/>{["Todos", ...statuses].map((item) => { const value = item === "Todos" ? "" : item; const label = item === "Todos" ? item : QUOTE_STATUS_CONFIG[item as typeof statuses[number]].label; return <Link key={item} href={`/presupuestos${value ? `?status=${value}` : ""}`} className={`rounded-full border px-3 py-2 text-xs ${selected === value ? "border-accent bg-accent-soft" : "border-surface-border"}`}>{label}</Link>; })}</form><div className="liquid-glass mt-5 overflow-hidden rounded-2xl"><div className="hidden grid-cols-[1.6fr_.8fr_.7fr_.8fr_.8fr] gap-3 border-b border-surface-border px-5 py-3 text-xs text-muted-foreground md:grid"><span>Cliente</span><span>Estado</span><span>Importe</span><span>Seguimiento</span><span>Responsable</span></div>{quotes.map((quote) => { const status = QUOTE_STATUS_CONFIG[quote.status]; const followUp = quote.events[0]?.startAt; return <Link key={quote.id} href={`/presupuestos/quotes/${quote.id}`} className="grid gap-2 border-b border-surface-border px-5 py-4 text-sm transition-colors hover:bg-foreground/5 md:grid-cols-[1.6fr_.8fr_.7fr_.8fr_.8fr]"><span className="font-medium">{quote.client?.name ?? "Contacto pendiente"}</span><span className={`w-fit rounded-full border px-2 py-0.5 text-xs ${status.badgeClassName}`}>{status.label}</span><span>{quote.total.toFixed(2)} {quote.currency ?? ""}</span><span className="text-muted-foreground">{followUp ? new Intl.DateTimeFormat("es-ES", { dateStyle: "medium" }).format(followUp) : "Sin seguimiento"}</span><span className="text-muted-foreground">{quote.responsible?.displayName ?? "Sin responsable"}</span></Link>; })}{quotes.length === 0 ? <p className="text-muted-foreground p-8 text-center text-sm">No hay presupuestos para este filtro.</p> : null}</div></div></div>;
}
